import "../../layouts/carousel";
import "../../layouts/similar-companies";
import "../../layouts/similar-equipment-types";
import "../../layouts/similar-locations";
import "../../components/tabs";
import "../../scripts/expand";
import "./map";
import "./sell";
import "./feedback";
